#Probar endpoint utilizando la extension de VSCode 'REST Client'
#y pulsando el boton 'Send Request' que aparece debajo de este mensaje

# obtiene todos los productos
GET http://localhost:8080/api/productos

###

# obtiene un producto por su id
GET http://localhost:8080/api/productos/1