PUT http://localhost:8080/api/productos/62f2e49b65c20d1835e53421
content-type: application/json

{
"name": "Yerba mate", "price": 280, "description": "Yerba mate elaborada con palo", 
"code": "YER", "stock": 25, "thumbnail": "https://www.taragui.com/img/products/x1.jpg.pagespeed.ic.0CLzXnsIOL.jpg" 
}
